"""Accès en lecture seule à data/pac_app.duckdb pour l'app Streamlit.

Base séparée de data/pac.duckdb (celle du pipeline discover/reviews/score,
cf. pac.config.DUCKDB_PATH) : APP_DUCKDB_PATH est un export allégé,
régénéré par `pac export-app-db` -- ne contient que ce que l'app affiche
réellement (cf. discussion : ~90% des avis bruts ne sont jamais lus par le
Streamlit, seuls ceux liés à une mention pain-au-chocolat/viennoiserie le
sont). L'app ne tourne donc plus en lecture concurrente du pipeline ;
chaque fonction publique reste décorée @st.cache_data avec un TTL court
pour limiter la fréquence de réouverture après une régénération."""

from pathlib import Path

import duckdb
import pandas as pd
import streamlit as st

from pac.config import APP_DUCKDB_PATH
from pac.webapp.theme import extract_arrondissement

CACHE_TTL_SECONDS = 60


class DatabaseUnavailable(RuntimeError):
    """La base n'existe pas encore, ou est momentanément inaccessible
    (verrouillée par une régénération concurrente via `pac export-app-db`)."""


def _connect() -> duckdb.DuckDBPyConnection:
    if not Path(APP_DUCKDB_PATH).exists():
        raise DatabaseUnavailable(
            f"{APP_DUCKDB_PATH} does not exist yet -- run `pac export-app-db` at least once."
        )
    try:
        return duckdb.connect(str(APP_DUCKDB_PATH), read_only=True)
    except duckdb.Error as exc:
        raise DatabaseUnavailable(
            "Database temporarily unavailable (probably being regenerated by "
            "`pac export-app-db`) -- try again in a few seconds."
        ) from exc


@st.cache_data(ttl=CACHE_TTL_SECONDS, show_spinner=False)
def load_places_with_scores() -> pd.DataFrame:
    """Un lieu par ligne, avec son score pain-au-chocolat s'il existe et
    son arrondissement dérivé de l'adresse."""
    con = _connect()
    try:
        df = con.execute(
            """
            WITH ranked AS (
                SELECT
                    p.*,
                    count(*) OVER (PARTITION BY p.lat, p.lon) AS n_at_coord
                FROM places p
            )
            SELECT
                p.place_id, p.name, p.formatted_address, p.lat, p.lon,
                p.rating AS google_rating, p.user_rating_count, p.google_maps_uri,
                s.score_10, s.confidence, s.n_relevant, s.n_mentions_total, s.positive_ratio
            FROM ranked p
            LEFT JOIN pac_scores s ON s.place_id = p.place_id
            WHERE p.lat IS NOT NULL AND p.lon IS NOT NULL
              -- écarte les fiches "fantômes" : coordonnées identiques à un
              -- autre lieu ET aucune donnée d'engagement Google (ni note ni
              -- nombre d'avis) -- signe qu'il s'agit d'une fiche
              -- obsolète/en double pour le même commerce physique (cf. plan),
              -- pas d'un commerce distinct (ceux-là ont presque toujours au
              -- moins quelques avis Google).
              AND NOT (p.n_at_coord > 1 AND p.rating IS NULL AND p.user_rating_count IS NULL)
            """
        ).fetchdf()
    finally:
        con.close()
    df["confidence"] = df["confidence"].fillna("insufficient_data")
    df["arrondissement"] = df["formatted_address"].apply(extract_arrondissement)
    return df


@st.cache_data(ttl=CACHE_TTL_SECONDS, show_spinner=False)
def load_kpis() -> dict:
    con = _connect()
    try:
        row = con.execute(
            """
            SELECT
                (SELECT count(*) FROM places) AS n_places,
                (SELECT count(*) FROM reviews) AS n_reviews,
                (SELECT count(*) FROM pac_scores WHERE score_10 IS NOT NULL) AS n_scored,
                (SELECT avg(score_10) FROM pac_scores WHERE score_10 IS NOT NULL) AS avg_score,
                (SELECT max(scraped_at) FROM reviews) AS last_review_at
            """
        ).fetchone()
    finally:
        con.close()
    n_places, n_reviews, n_scored, avg_score, last_review_at = row
    return {
        "n_places": n_places or 0,
        "n_reviews": n_reviews or 0,
        "n_scored": n_scored or 0,
        "coverage_pct": (n_scored / n_places * 100) if n_places else 0.0,
        "avg_score": avg_score,
        "last_review_at": last_review_at,
    }


@st.cache_data(ttl=CACHE_TTL_SECONDS, show_spinner=False)
def load_mentions_for_place(place_id: str) -> pd.DataFrame:
    """Avis pain-au-chocolat retenus (relevant = true) pour UN lieu, triés
    des plus positifs aux plus négatifs -- pour le défilement complet des
    avis d'une boulangerie dans le panneau de détail de la carte et
    l'onglet "Near an address".

    Requête ciblée par place_id plutôt qu'un chargement + groupby de TOUTE
    la table pac_mentions (essayé avant : ~1200 lieux regroupés en dicts de
    DataFrame juste pour n'en lire qu'un seul à la fois) -- mesuré ~20x plus
    rapide, et surtout évite que st.cache_data recopie un gros dict entier
    à chaque rerun (chaque clic sur un marqueur) alors qu'un seul lieu est
    affiché à la fois (cf. plan performance)."""
    con = _connect()
    try:
        return con.execute(
            """
            SELECT m.sentiment, m.reason, r.text, r.author_name,
                   r.rating, r.relative_time_text, r.published_at
            FROM pac_mentions m
            JOIN reviews r ON r.review_id = m.review_id
            WHERE m.relevant = true AND m.place_id = ?
            ORDER BY m.sentiment DESC
            """,
            [place_id],
        ).fetchdf()
    finally:
        con.close()
